spring:
  profiles:
    active: prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: sibsankar2727@gmail.com
    password: ekuf ojsc mues ynvm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: fe0a296860c294b3463ff09af9a162bd

logging:
  file:
    name: spring-boot-app.log
