spring:
  data:
    mongodb:
      uri: mongodb+srv://sibsankar_db_user:Mo8sGwtc94SWdMVm@cluster0.nlxznzv.mongodb.net/journaldb?appName=Cluster0&serverSelectionTimeoutMS=10000&tls=true
      database: journaldb
      auto-index-creation: true

server:
  port: 8080